on:
  push:
    branches: [main, master, devel]
  pull_request:
    branches: [main, master, devel]

name: check-rtools-versions

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          #- {os: windows-latest, r: 'devel', rtools: '45'}
          - {os: windows-latest, r: 'next' , rtools: '45'}
          - {os: windows-latest, r: '4.4'  , rtools: '44'}
          - {os: windows-latest, r: '4.3'  , rtools: '43'}
          - {os: windows-latest, r: '4.2'  , rtools: '42'}
          - {os: windows-latest, r: '4.1'  , rtools: '40'}
          - {os: windows-latest, r: '4.0'  , rtools: '40'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          rtools-version: ${{ matrix.config.rtools }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
